### ISSUE TITLE
Bottle GLPK 4.61

### ISSUE THREAD

**Issue by mlubin** [staticfloat/homebrew-juliadeps#117]
Could we bottle GLPK 4.61 to match the version we now use on Linux? (https://github.com/JuliaOpt/GLPK.jl/pull/34)
I don't believe any changes are needed in the compile script.

Thanks!

@staticfloat @yeesian @tkelman

**Comment by staticfloat** [comment]
@mlubin how big of a problem is it for the minor version number to change?  You could just change [this line](https://github.com/JuliaOpt/GLPK.jl/blob/d3d3bf632346824c22cf1f7fca6983fdf6c18cc8/deps/build.jl#L40) to say `homebrew/science/glpk` instead of `glpk452` and you'll get `glpk v4.6.1` installed, but that will update along with Homebrew.  If that's a problem, we can, of course, bottle a frozen version called `staticfloat/juliadeps/glpk461`, but otherwise, it reduces maintenance burden here to just use the Homebrew/science version, so I try to encourage that whenever I can.

**Comment by mlubin** [comment]
GLPK can introduce breaking API changes between versions. If we can't put an upper bound on the version installed by ``homebrew/science/glpk`` then we'd be setting ourselves up for uncontrolled breakage down the line.

**Comment by ararslan** [comment]
Homebrew has a way of specifying versions now, IIRC, something like `glpk@4.6.1`

**Comment by staticfloat** [comment]
@mlubin alright, try running with the formula name set to `staticfloat/juliadeps/glpk461` now.

**Comment by mlubin** [comment]
Appears to be working, thanks!
