### ISSUE TITLE
Add bottle for librsvg

### ISSUE THREAD

**Issue by spencerlyon2** [staticfloat/homebrew-juliadeps#87]
I would like to get Homebrew.jl support for librsvg. 

Homebrew already bottles this (see [formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/librsvg.rb)) but without `cellar :any`. 

I've never written a homebrew formula before, but would be happy to test and try things out. Do you think you could help me out?

Thanks @staticfloat

**Comment by staticfloat** [comment]
Hey @spencerlyon2, sorry for the late response.  Here are the steps that I take whenever something like this happens.  I'm thinking out loud here, so follow along if you're interested:

* First, I look for a previous formula.  You've found one, although it doesn't have `cellar :any`.  As Pooh would say, "Oh bother".

* Next, I look into why it might not be `cellar :any` already.  I install it with `brew install -v --build-bottle librsvg`, which complete successfully, then run `brew bottle -v librsvg`, which outputs:

```
$ brew bottle -v librsvg
==> Determining librsvg bottle revision...
==> Bottling librsvg-2.40.13.yosemite.bottle.1.tar.gz...
/usr/bin/touch -h -t 201601071744.53 /usr/local/Cellar/librsvg/2.40.13/lib/librsvg-2.dylib
tar cf /Users/sabae/librsvg-2.40.13.yosemite.bottle.1.tar librsvg/2.40.13
gzip -f librsvg-bottle.tar
Warning: String '/usr/local/Cellar' still exists in these files:
/usr/local/Cellar/librsvg/2.40.13/lib/girepository-1.0/Rsvg-2.0.typelib
 --> match '/usr/local/Cellar/librsvg/2.40.13/lib/librsvg-2.2.dylib' at offset 0x130

./librsvg-2.40.13.yosemite.bottle.1.tar.gz
  bottle do
    revision 1
    sha256 "d6a69c90e541cfa62205123d187f1d809a5e2bedd60bb91817ac592dcc9c907d" => :yosemite
  end
```

That warning might be something we need to worry about, since hardcoded paths like that can be bad.  However, I like to be cavalier about things that may or may not be a problem, so I'll just go ahead and bottle this guy as-is.

* I then need to copy the formula over to my tap on the `staging` branch, for building.  I've done that [here](https://github.com/staticfloat/homebrew-juliadeps/commit/1191f22a1012b4f9d513739c4bbb76b965d4d9cb).

* Next up, I build the bottles on https://build.julialang.org, the status of which is visible for the OSX [10.9](https://build.julialang.org/builders/bottle_osx10.9-x64/builds/5), [10.10](https://build.julialang.org/builders/bottle_osx10.10-x64/builds/9), and [10.11](https://build.julialang.org/builders/bottle_osx10.11-x64/builds/9) buildbots separately.

**Comment by spencerlyon2** [comment]
Hey @staticfloat no problem, thanks for working through this and giving me enough details to know what happens. I should hopefully be able to do some of the legwork myself next time.

So what's the next step? Anything I can do to help you get this finished up so I can depend on it from a package?

**Comment by staticfloat** [comment]
Next steps:

* Look at the builders we ordered to build the bottles last time, and see if any failed. (One did, [the 10.9 one](https://build.julialang.org/builders/bottle_osx10.9-x64/builds/5/steps/shell/logs/stdio) due to some icu4c download error.  I've [rebuilt that one](https://build.julialang.org/builders/bottle_osx10.9-x64/builds/6/steps/shell/logs/stdio), so now everything looks good, and we can continue.

* The bottles have been automatically uploaded into their proper places on our AWS server, so now we need to edit the formula we copied over into my tap earlier to have the proper `bottle` stanza.  This has been done [here](https://github.com/staticfloat/homebrew-juliadeps/commit/ffd66bab3ac59d271a7b350e253e5fcd48ececa6).  (Basically, set the bottle server URL, set SHA256 hashes for each bottle, and tell brew that it's a `cellar :any` bottle).

* Finally, this must be merged onto the `master` branch, so that when people do a `using Homebrew; Homebrew.update()`, they get the new, sweet formulae!  Go ahead and try it, and please make sure this formula works for you!

**Comment by staticfloat** [comment]
Ah, I forgot one minor point; we need to do this for every dependency as well.  Luckily, all dependencies were already `cellar :any`, and the only real change needed to be done was to copy `libcroco` over to my tap for annoying technical reasons.  (Because it relies on things like `glib` which are not `cellar :any` in the main repository but are in my tap, we have to copy it over and replace the `glib` dependency with `staticfloat/juliadeps/glib`, etc...)   I can install `librsvg` with `Homebrew.update(); Homebrew.add("librsvg")`, and then ensure things with with `Libdl.dlopen("librsvg-2")`.

**Comment by spencerlyon2** [comment]
Thank you for working on this. It works seamlessly for me!
